### ISSUE TITLE
How to train my own PerceiverIO

### ISSUE THREAD

**Issue by wanggsz** [JOBR0/PerceiverIO_Pytorch#1]
Hi, 

Thank you so much for this fantastic repo! Yet I couldn't find the trainer for it.
I'm building my own PerceiverIO for a specific task. I wonder if there's any training code for PerceiverIO?

Many thanks!

**Comment by JOBR0** [comment]
Unfortunately I don't have any PyTorch training code. The original deepmind repository has some training code but it's jax/haiku.

**Comment by wanggsz** [comment]
> Unfortunately I don't have any PyTorch training code. The original deepmind repository has some training code but it's jax/haiku.

Yeah... I noticed that. Anyway, thanks a lot!
